export const WORLD_SIZE = 800;           // metrów, teren 800×800
export const TERRAIN_RES = 64;           // 64×64 heightmap
export const TERRAIN_HEIGHT_SCALE = 0;   // płaska mapa
export const CAR_MASS = 800;             // kg chassis
export const MAX_ENGINE_FORCE = 6750;    // N (+50%)
export const MAX_STEER = 0.5;            // rad
export const BRAKE_FORCE = 60;
export const CAMERA_OFFSET_BEHIND = 10;
export const CAMERA_OFFSET_UP = 4;
export const CAMERA_LERP = 0.06;
export const STARTING_TIME = 60;         // sekund na start
